USE "234a_FueledByJava";


SELECT FBJ_USER.Email
	,FBJ_ITEM.Name
	,COUNT(CASE WHEN FBJ_RESULT.Value = 1 THEN 1 END) AS [Wins]
	,COUNT(CASE WHEN FBJ_RESULT.Value = -1 THEN -1 END) AS Losses
	,COUNT(CASE WHEN FBJ_RESULT.Value = 0 THEN 0 END) AS [Ties]
FROM FBJ_USER
JOIN FBJ_TEST ON FBJ_USER.PK_UserID = FBJ_TEST.FK_UserID
JOIN FBJ_RESULT ON FBJ_TEST.PK_TestID = FBJ_RESULT.FK_TestID
JOIN FBJ_ITEM ON FBJ_ITEM.PK_ItemID = FBJ_RESULT.FK_Item1ID
WHERE FBJ_USER.Email = 'chunwei.li@pcc.edu'
GROUP BY FBJ_USER.Email, FBJ_ITEM.Name

SELECT FBJ_USER.Email
FROM FBJ_USER;

SELECT * FROM FBJ_RESULT;