package edu.pcc.fbj.rankingsystem.resultreporting;

/**
 * @author David Li
 * @version 2016.05.19
 */
public enum Signal
{
    DATABASE_SIGNAL_THREAD_WAIT,
    DATABASE_SIGNAL_THREAD_TERMINATE,
    DATABASE_SIGNAL_UPDATE_EAMIL_LIST,
    DATABASE_SIGNAL_UPDATE_TESTNAME_LIST,
    DATABASE_SIGNAL_UPDATE_TESTID_LIST,
    DATABASE_SIGNAL_RETRIEVE_DATA,
    DATABASE_SIGNAL_RETRIEVE_MATRIX_DATA,
    DATABASE_SIGNAL_RETRIEVE_STATISTICS_FIRSTCHOICE_DATA,
    DATABASE_SIGNAL_RETRIEVE_STATISTICS_XOVERY_DATA
}
